version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://counseling_user:counseling_password@db:5432/counseling_db
      - ENVIRONMENT=development
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=counseling_db
      - POSTGRES_USER=counseling_user
      - POSTGRES_PASSWORD=counseling_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgvector_db:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_DB=counseling_vector_db
      - POSTGRES_USER=vector_user
      - POSTGRES_PASSWORD=vector_password
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pgvector_data: